language: node_js
node_js:
  - '10'
script:
  - yarn test
  - yarn build
before_deploy:
  - TAG=$(git describe --match [0-9].[0-9].[0-9]* --abbrev=7 --tags HEAD | sed -e 's/-\([0-9]*\)-g/+\1.sha-/g')
  - echo "$(sed -e 's/0.0.0-PLACEHOLDER/'"$TAG"'/g' package.json)" > package.json
  - echo "Publishing to npm, version $TAG"
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN_FAKE'
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: true
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always

