language: node_js
node_js:
  - '10'
script:
  - 'yarn test'
  - 'echo "$(sed -e "s/0.0.0-PLACEHOLDER/$TRAVIS_TAG/g" package.json)" > package.json'
  - 'yarn build'
before_deploy:
  - 'echo "Publishing to npm, version $TRAVIS_TAG"'
deploy:
  - provider: npm
    email: '$NPM_EMAIL'
    api_key: '$NPM_TOKEN'
    skip_cleanup: true
    tag: next
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+$
  - provider: npm
    email: '$NPM_EMAIL'
    api_key: '$NPM_TOKEN'
    skip_cleanup: true
    tag: latest
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$
notifications:
  email: true
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always
